### ISSUE TITLE
Fails to run migrations on blank database

### ISSUE THREAD

**Issue by singpolyma** [madssj/django-longer-username-and-email#13]
Because Django tries to run this app's migrations before even the migrations that create the User to begin with...

**Comment by madssj** [comment]
This project is not really meant to be used on newer django installations or projects and I'd be very surprised if it works.

What problem are you trying to solve by including it, and what django version are you using?

**Comment by singpolyma** [comment]
Using Django 1.6.4 -- the app was in as a dependency when I inherited this project, and the issue is affecting me because I'm trying to provision new boxes.

**Comment by madssj** [comment]
Feel free to fork and PR, should be easily solvable with a south dependency.

**Comment by singpolyma** [comment]
Looks like the dependencies require that I name the app the migration I depend on is in.  But won't the migration always be in an app named whatever the Django app is named?  In my case it's called "core" it looks like, but I'm not sure that's always going to be true...

**Comment by singpolyma** [comment]
Oh, I see, it's in `django.contrib.auth`

**Comment by singpolyma** [comment]
Or not. There's no actual migrations in there... just the model.  How does the users table get created in the first place?

**Comment by madssj** [comment]
You mean `syncdb`?

**Comment by madssj** [comment]
In any case, it doesn't seem like there's an actual issue here.

**Comment by singpolyma** [comment]
It seems like if we run  `syncdb --all` and then `migrate --fake` we get something that works for now.  I think.
