### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by hwkns** [madssj/django-longer-username-and-email#7]
Does django-longer-username-and-email support Python 3?

If so, it would be nice to designate that on PyPI using classifiers in setup.py (see https://pypi.python.org/pypi?%3Aaction=list_classifiers)

If not, what does the path forward look like?

**Comment by madssj** [comment]
I'm closing this issue. If anyone either wants to pay me, or send a PR I'm all for re-opening.

**Comment by hwkns** [comment]
Turns out it does work with py3.  It does not work with Django 1.7 yet.
