### ISSUE TITLE
Email issue on django 1.5.5

### ISSUE THREAD

**Issue by weiztech** [madssj/django-longer-username-and-email#8]
Hi , i try to test this apps using default settings and put the apps on top of installed app

the migrate look's working but when we want to save new user with long email . its' said 
"DatabaseError: value too long for type character varying(75)" (i check its alredy changed to 255 on schema db)

anyone here have this problem before ?

**Comment by madssj** [comment]
I myself have not experienced this before. Feel free to post more details if you uncover any.

**Comment by madssj** [comment]
I'm closing this issue. Feel free to add any more information if you have any.
